/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Swing;

/**
 *
 * @author TechCare
 */
public class Calculators extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public Calculators() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jBtn1 = new javax.swing.JButton();
        jBtn2 = new javax.swing.JButton();
        jBtn18 = new javax.swing.JButton();
        jBtn19 = new javax.swing.JButton();
        jBtn20 = new javax.swing.JButton();
        jBtn21 = new javax.swing.JButton();
        jBtn22 = new javax.swing.JButton();
        jBtn23 = new javax.swing.JButton();
        jBtn24 = new javax.swing.JButton();
        jBtn25 = new javax.swing.JButton();
        jBtn26 = new javax.swing.JButton();
        jBtn27 = new javax.swing.JButton();
        jBtn28 = new javax.swing.JButton();
        jBtn29 = new javax.swing.JButton();
        jBtn30 = new javax.swing.JButton();
        jBtn31 = new javax.swing.JButton();
        jBtn32 = new javax.swing.JButton();
        jBtn33 = new javax.swing.JButton();
        jBtn35 = new javax.swing.JButton();
        jBtn34 = new javax.swing.JButton();
        jBtn36 = new javax.swing.JButton();
        jBtn37 = new javax.swing.JButton();
        jBtn38 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jBtn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn1.setText("OFF");

        jBtn2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn2.setText("ON");
        jBtn2.setMaximumSize(new java.awt.Dimension(67, 31));
        jBtn2.setMinimumSize(new java.awt.Dimension(67, 31));
        jBtn2.setPreferredSize(new java.awt.Dimension(67, 31));

        jBtn18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn18.setText("AC");

        jBtn19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn19.setText("√");
        jBtn19.setMaximumSize(new java.awt.Dimension(67, 31));
        jBtn19.setMinimumSize(new java.awt.Dimension(67, 31));
        jBtn19.setPreferredSize(new java.awt.Dimension(67, 31));
        jBtn19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn19ActionPerformed(evt);
            }
        });

        jBtn20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn20.setText("%");
        jBtn20.setMaximumSize(new java.awt.Dimension(67, 31));
        jBtn20.setMinimumSize(new java.awt.Dimension(67, 31));
        jBtn20.setPreferredSize(new java.awt.Dimension(67, 31));

        jBtn21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn21.setText("1/x");
        jBtn21.setMaximumSize(new java.awt.Dimension(67, 31));
        jBtn21.setMinimumSize(new java.awt.Dimension(67, 31));
        jBtn21.setPreferredSize(new java.awt.Dimension(67, 31));

        jBtn22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn22.setText("x²");
        jBtn22.setMaximumSize(new java.awt.Dimension(67, 31));
        jBtn22.setMinimumSize(new java.awt.Dimension(67, 31));
        jBtn22.setPreferredSize(new java.awt.Dimension(67, 31));

        jBtn23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn23.setText("÷");
        jBtn23.setToolTipText("");
        jBtn23.setMaximumSize(new java.awt.Dimension(67, 31));
        jBtn23.setMinimumSize(new java.awt.Dimension(67, 31));
        jBtn23.setPreferredSize(new java.awt.Dimension(67, 31));
        jBtn23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn23ActionPerformed(evt);
            }
        });

        jBtn24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn24.setText("-");
        jBtn24.setMaximumSize(new java.awt.Dimension(67, 31));
        jBtn24.setMinimumSize(new java.awt.Dimension(67, 31));
        jBtn24.setPreferredSize(new java.awt.Dimension(67, 31));

        jBtn25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn25.setText("1");
        jBtn25.setMaximumSize(new java.awt.Dimension(67, 31));
        jBtn25.setMinimumSize(new java.awt.Dimension(67, 31));
        jBtn25.setPreferredSize(new java.awt.Dimension(67, 31));

        jBtn26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn26.setText("2");
        jBtn26.setMaximumSize(new java.awt.Dimension(67, 31));
        jBtn26.setMinimumSize(new java.awt.Dimension(67, 31));
        jBtn26.setPreferredSize(new java.awt.Dimension(67, 31));

        jBtn27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn27.setText("3");
        jBtn27.setMaximumSize(new java.awt.Dimension(67, 31));
        jBtn27.setMinimumSize(new java.awt.Dimension(67, 31));
        jBtn27.setPreferredSize(new java.awt.Dimension(67, 31));

        jBtn28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn28.setText("+");
        jBtn28.setMaximumSize(new java.awt.Dimension(67, 31));
        jBtn28.setMinimumSize(new java.awt.Dimension(67, 31));
        jBtn28.setPreferredSize(new java.awt.Dimension(67, 31));

        jBtn29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn29.setText("4");
        jBtn29.setMaximumSize(new java.awt.Dimension(67, 31));
        jBtn29.setMinimumSize(new java.awt.Dimension(67, 31));
        jBtn29.setPreferredSize(new java.awt.Dimension(67, 31));

        jBtn30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn30.setText("5");
        jBtn30.setMaximumSize(new java.awt.Dimension(67, 31));
        jBtn30.setMinimumSize(new java.awt.Dimension(67, 31));
        jBtn30.setPreferredSize(new java.awt.Dimension(67, 31));

        jBtn31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn31.setText("6");
        jBtn31.setMaximumSize(new java.awt.Dimension(67, 31));
        jBtn31.setMinimumSize(new java.awt.Dimension(67, 31));
        jBtn31.setPreferredSize(new java.awt.Dimension(67, 31));

        jBtn32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn32.setText("=");
        jBtn32.setMaximumSize(new java.awt.Dimension(67, 31));
        jBtn32.setMinimumSize(new java.awt.Dimension(67, 31));
        jBtn32.setPreferredSize(new java.awt.Dimension(67, 31));

        jBtn33.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn33.setText("0");
        jBtn33.setMaximumSize(new java.awt.Dimension(67, 31));
        jBtn33.setMinimumSize(new java.awt.Dimension(67, 31));
        jBtn33.setPreferredSize(new java.awt.Dimension(67, 31));

        jBtn35.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn35.setText(".");
        jBtn35.setMaximumSize(new java.awt.Dimension(67, 31));
        jBtn35.setMinimumSize(new java.awt.Dimension(67, 31));
        jBtn35.setPreferredSize(new java.awt.Dimension(67, 31));

        jBtn34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn34.setText("*");
        jBtn34.setMaximumSize(new java.awt.Dimension(67, 31));
        jBtn34.setMinimumSize(new java.awt.Dimension(67, 31));
        jBtn34.setPreferredSize(new java.awt.Dimension(67, 31));

        jBtn36.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn36.setText("7");
        jBtn36.setMaximumSize(new java.awt.Dimension(67, 31));
        jBtn36.setMinimumSize(new java.awt.Dimension(67, 31));
        jBtn36.setPreferredSize(new java.awt.Dimension(67, 31));

        jBtn37.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn37.setText("8");
        jBtn37.setMaximumSize(new java.awt.Dimension(67, 31));
        jBtn37.setMinimumSize(new java.awt.Dimension(67, 31));
        jBtn37.setPreferredSize(new java.awt.Dimension(67, 31));

        jBtn38.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn38.setText("9");
        jBtn38.setMaximumSize(new java.awt.Dimension(67, 31));
        jBtn38.setMinimumSize(new java.awt.Dimension(67, 31));
        jBtn38.setPreferredSize(new java.awt.Dimension(67, 31));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jBtn18, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jBtn36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jBtn29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jBtn25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jBtn20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(12, 12, 12)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jBtn21, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jBtn22, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jBtn26, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jBtn27, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jBtn30, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jBtn31, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jBtn37, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jBtn38, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(14, 14, 14)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtn33, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtn35, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtn32, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jBtn34, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jBtn28, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jBtn24, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jBtn23, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jBtn19, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn18, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn19, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn20, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn21, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn22, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn23, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn25, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn26, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn27, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn24, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn29, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn30, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn31, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn28, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn36, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn37, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn38, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn34, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn33, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn35, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn32, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn19ActionPerformed

    private void jBtn23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn23ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculators.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculators.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculators.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculators.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculators().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn1;
    private javax.swing.JButton jBtn18;
    private javax.swing.JButton jBtn19;
    private javax.swing.JButton jBtn2;
    private javax.swing.JButton jBtn20;
    private javax.swing.JButton jBtn21;
    private javax.swing.JButton jBtn22;
    private javax.swing.JButton jBtn23;
    private javax.swing.JButton jBtn24;
    private javax.swing.JButton jBtn25;
    private javax.swing.JButton jBtn26;
    private javax.swing.JButton jBtn27;
    private javax.swing.JButton jBtn28;
    private javax.swing.JButton jBtn29;
    private javax.swing.JButton jBtn30;
    private javax.swing.JButton jBtn31;
    private javax.swing.JButton jBtn32;
    private javax.swing.JButton jBtn33;
    private javax.swing.JButton jBtn34;
    private javax.swing.JButton jBtn35;
    private javax.swing.JButton jBtn36;
    private javax.swing.JButton jBtn37;
    private javax.swing.JButton jBtn38;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
